"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class HubAccessLevelEnum(str, Enum):
    DIRECT_ONLY = 'DIRECT_ONLY'
    ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS'
    INVITED_TO_HUB = 'INVITED_TO_HUB'
    HUB_ACCESS = 'HUB_ACCESS'
