"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class IncomingMeldFrequencyEnum(str, Enum):
    IMMEDIATELY = 'IMMEDIATELY'
    DAILY = 'DAILY'
    NEVER = 'NEVER'
