"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import meldlistviewmanagementagent as shared_meldlistviewmanagementagent
from dataclasses_json import Undefined, dataclass_json
from meldapi import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class MeldListViewInHouseMeldServicer:
    agent: shared_meldlistviewmanagementagent.MeldListViewManagementAgent = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('agent') }})
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    

