"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class MethodEnum(str, Enum):
    CASH = 'CASH'
    ACH = 'ACH'
    CHECK = 'CHECK'
    CC = 'CC'
