"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class NullEnum(str, Enum):
    LESS_THAN_NIL_GREATER_THAN_ = '<nil>'
