"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import address as shared_address
from dataclasses_json import Undefined, dataclass_json
from meldapi import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PatchedUnitInput:
    approval_currency_limit: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('approval_currency_limit'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'approval_currency_limit' }, 'multipart_form': { 'field_name': 'approval_currency_limit' }})
    current_residents: Optional[list[int]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('current_residents'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'current_residents' }, 'multipart_form': { 'field_name': 'current_residents' }})
    maintenance_notes: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('maintenance_notes'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'maintenance_notes' }, 'multipart_form': { 'field_name': 'maintenance_notes' }})
    property_id: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('property_id'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'property_id' }, 'multipart_form': { 'field_name': 'property_id' }})
    unit: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('unit'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'unit' }, 'multipart_form': { 'field_name': 'unit' }})
    r"""This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302"""
    unit_address: Optional[shared_address.Address] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('unit_address'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'unit_address', 'json': True }, 'multipart_form': { 'field_name': 'unit_address', 'json': True }})
    

