"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from meldapi import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PatchedPropertyInput:
    city: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('city'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'city' }, 'multipart_form': { 'field_name': 'city' }})
    country: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('country'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'country' }, 'multipart_form': { 'field_name': 'country' }})
    county_province: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('county_province'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'county_province' }, 'multipart_form': { 'field_name': 'county_province' }})
    line_1: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('line_1'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'line_1' }, 'multipart_form': { 'field_name': 'line_1' }})
    line_2: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('line_2'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'line_2' }, 'multipart_form': { 'field_name': 'line_2' }})
    line_3: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('line_3'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'line_3' }, 'multipart_form': { 'field_name': 'line_3' }})
    maintenance_notes: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('maintenance_notes'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'maintenance_notes' }, 'multipart_form': { 'field_name': 'maintenance_notes' }})
    other_address_details: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('other_address_details'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'other_address_details' }, 'multipart_form': { 'field_name': 'other_address_details' }})
    owners: Optional[list[int]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('owners'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'owners' }, 'multipart_form': { 'field_name': 'owners' }})
    postcode: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('postcode'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'postcode' }, 'multipart_form': { 'field_name': 'postcode' }})
    property_groups: Optional[list[int]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('property_groups'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'property_groups' }, 'multipart_form': { 'field_name': 'property_groups' }})
    property_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('property_name'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'property_name' }, 'multipart_form': { 'field_name': 'property_name' }})
    units: Optional[list[int]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('units'), 'exclude': lambda f: f is None }, 'form': { 'field_name': 'units' }, 'multipart_form': { 'field_name': 'units' }})
    

