"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ProjectTypeEnum(str, Enum):
    OTHER = 'OTHER'
    RENOVATION = 'RENOVATION'
    TURN = 'TURN'
    MITIGATION = 'MITIGATION'
