"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class StatusD0bEnum(str, Enum):
    DRAFT = 'DRAFT'
    IN_REVIEW = 'IN_REVIEW'
    HOLD = 'HOLD'
    APPROVED = 'APPROVED'
    BILLED = 'BILLED'
