"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Status09fEnum(str, Enum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    IN_REVIEW = 'IN_REVIEW'
    HOLD = 'HOLD'
    DECLINED = 'DECLINED'
    APPROVED = 'APPROVED'
    PAID = 'PAID'
