"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import paginatedestimateserializerlistlist as shared_paginatedestimateserializerlistlist
from enum import Enum
from typing import Optional


@dataclasses.dataclass
class EstimatesListSecurity:
    
    pmo_auth2_authentication: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    
class EstimatesListEstimateStatus(str, Enum):
    ESTIMATE_APPROVED = 'ESTIMATE_APPROVED'
    ESTIMATE_CLOSED = 'ESTIMATE_CLOSED'
    ESTIMATE_IN_PROGRESS = 'ESTIMATE_IN_PROGRESS'
    ESTIMATE_OWNER_REJECTED = 'ESTIMATE_OWNER_REJECTED'
    ESTIMATE_PENDING_ACCEPTANCE = 'ESTIMATE_PENDING_ACCEPTANCE'
    ESTIMATE_PENDING_APPROVAL = 'ESTIMATE_PENDING_APPROVAL'
    ESTIMATE_SUBMITTED = 'ESTIMATE_SUBMITTED'
    ESTIMATE_VENDOR_REJECTED = 'ESTIMATE_VENDOR_REJECTED'


@dataclasses.dataclass
class EstimatesListRequest:
    
    x_pm_org: int = dataclasses.field(metadata={'header': { 'field_name': 'X-Pm-Org', 'style': 'simple', 'explode': False }})
    r"""The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123"""
    estimate_status: Optional[list[EstimatesListEstimateStatus]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'estimate_status', 'style': 'form', 'explode': True }})
    limit: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    r"""Number of results to return per page."""
    offset: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': True }})
    r"""The initial index from which to return the results."""
    ordering: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'ordering', 'style': 'form', 'explode': True }})
    r"""Which field to use when ordering the results."""
    

@dataclasses.dataclass
class EstimatesListResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    paginated_estimate_serializer_list_list: Optional[shared_paginatedestimateserializerlistlist.PaginatedEstimateSerializerListList] = dataclasses.field(default=None)
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    