"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import paginatedmeldinvoiceserializerlistlist as shared_paginatedmeldinvoiceserializerlistlist
from enum import Enum
from typing import Optional


@dataclasses.dataclass
class InvoiceListSecurity:
    
    pmo_auth2_authentication: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    
class InvoiceListDeclined(str, Enum):
    r"""declined"""
    TRUE = 'true'
    FALSE = 'false'

class InvoiceListPaid(str, Enum):
    r"""paid"""
    FALSE = 'false'
    TRUE = 'true'

class InvoiceListStatus(str, Enum):
    r"""status"""
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    IN_REVIEW = 'IN_REVIEW'
    HOLD = 'HOLD'
    DECLINED = 'DECLINED'
    APPROVED = 'APPROVED'
    PAID = 'PAID'


@dataclasses.dataclass
class InvoiceListRequest:
    
    x_pm_org: int = dataclasses.field(metadata={'header': { 'field_name': 'X-Pm-Org', 'style': 'simple', 'explode': False }})
    r"""The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123"""
    created_gte: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'created__gte', 'style': 'form', 'explode': True }})
    r"""created__gte"""
    created_interval: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'created__interval', 'style': 'form', 'explode': True }})
    r"""created__interval"""
    created_lte: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'created__lte', 'style': 'form', 'explode': True }})
    r"""created__lte"""
    declined: Optional[InvoiceListDeclined] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'declined', 'style': 'form', 'explode': True }})
    r"""declined"""
    limit: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    r"""Number of results to return per page."""
    offset: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': True }})
    r"""The initial index from which to return the results."""
    ordering: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'ordering', 'style': 'form', 'explode': True }})
    r"""Which field to use when ordering the results."""
    paid: Optional[InvoiceListPaid] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'paid', 'style': 'form', 'explode': True }})
    r"""paid"""
    payment_requested_gte: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'payment_requested__gte', 'style': 'form', 'explode': True }})
    r"""payment_requested__gte"""
    payment_requested_interval: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'payment_requested__interval', 'style': 'form', 'explode': True }})
    r"""payment_requested__interval"""
    payment_requested_lte: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'payment_requested__lte', 'style': 'form', 'explode': True }})
    r"""payment_requested__lte"""
    status: Optional[InvoiceListStatus] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'status', 'style': 'form', 'explode': True }})
    r"""status"""
    vendor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'vendor', 'style': 'form', 'explode': True }})
    r"""vendor"""
    vendors: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'vendors', 'style': 'form', 'explode': True }})
    r"""vendors"""
    

@dataclasses.dataclass
class InvoiceListResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    paginated_meld_invoice_serializer_list_list: Optional[shared_paginatedmeldinvoiceserializerlistlist.PaginatedMeldInvoiceSerializerListList] = dataclasses.field(default=None)
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    