"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import vendorinvite as shared_vendorinvite
from typing import Optional


@dataclasses.dataclass
class VendorInviteCreateSecurity:
    
    pmo_auth2_authentication: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class VendorInviteCreateRequest:
    
    vendor_invite: shared_vendorinvite.VendorInvite = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    x_pm_org: int = dataclasses.field(metadata={'header': { 'field_name': 'X-Pm-Org', 'style': 'simple', 'explode': False }})
    r"""The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123"""
    

@dataclasses.dataclass
class VendorInviteCreateResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    vendor_invite: Optional[shared_vendorinvite.VendorInvite] = dataclasses.field(default=None)
    